source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "aws-sdk-s3"
gem "sidekiq", "~> 7.0"
gem "redis", "~> 5.0"
gem "dotenv-rails", groups: [ :development, :test ]

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "webmock"
  gem "shoulda-matchers"
end

group :test do
  gem "database_cleaner-active_record"
  gem "simplecov", require: false
end
